language: ruby
rvm:
  - '2.1.1'
addons:
  postgresql: "9.3"

env:
 ­- DB=postgresql
script:
­ - RAILS_ENV=test bundle exec rake db:migrate ­­--trace ­ 
 - bundle exec rake
before_script:
­ - cp config/database.yml.sample config/database.yml ­
 -  psql ­c 'create database pm_test' ­U postgres
