# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

local: &local 
  adapter: postgresql 
  username: davudovali
  password: 22ad88em
  host: localhost

development:
  <<: *local 
  database: omega_project_dev

test:
  <<: *local
  database: omega_project_test

production:
  <<: *local
  database: omega_project_production